language: rust

before_install:
  - set -e
  - export RUSTFLAGS="-D warnings"
  - rustup self update
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo check --tests
