[package]
name = "headless_chrome"
version = "0.0.1"
authors = ["Alistair Roche <roche.a@gmail.com>"]
edition = "2018"

[dependencies]
websocket = "0.21.1"
regex = "1"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
serde_derive = "1"
failure = "0.1.5"
log = "0.4.5"
env_logger = "0.5.13"
rand = "0.6"

[lib]
name = "lib"
path = "src/lib.rs"
