[package]
name = "myws"
version = "0.1.0"
authors = ["Alistair Roche <roche.a@gmail.com>"]

[dependencies]
websocket = "0.20.2"
regex = "1"
serde_json = "1.0"
serde = "1.0.78"
serde_derive = "1.0.78"
cdp={git="https://github.com/devtools-html/rust-cdp.git"}