[package]
name = "headless_chrome"
version = "0.1.1"
authors = ["Alistair Roche <alistair@sunburnt.country>"]
edition = "2018"
description = "Control Chrome programatically"
license = "MIT"
homepage = "https://github.com/atroche/rust-headless-chrome"
repository = "https://github.com/atroche/rust-headless-chrome"
readme = "README.md"

[dependencies]
websocket = "0.21.1"
regex = "1"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
serde_derive = "1"
failure = "0.1.5"
log = "0.4.5"
env_logger = "0.5.13"
rand = "0.6"
tempdir = "0.3"
toml = "0.4"
chrono = "0.4"
termcolor = "1"

[lib]
name = "headless_chrome"
path = "src/lib.rs"
